// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrbEIgLV2d6Gc9yPzs9UvsHE1VgExGvwY',
    appId: '1:994080503904:web:cb446b490b17b202ed6b05',
    messagingSenderId: '994080503904',
    projectId: 'chatapp-b5aeb',
    authDomain: 'chatapp-b5aeb.firebaseapp.com',
    storageBucket: 'chatapp-b5aeb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmh7L7BXs9vFVBwHskIN_8yBZLvUL_6pk',
    appId: '1:994080503904:android:5d540c79e7d8bb7fed6b05',
    messagingSenderId: '994080503904',
    projectId: 'chatapp-b5aeb',
    storageBucket: 'chatapp-b5aeb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnt0PiOAWnVqIJg8prDjgS-bAaGbet6BY',
    appId: '1:994080503904:ios:de472e0f2294b36eed6b05',
    messagingSenderId: '994080503904',
    projectId: 'chatapp-b5aeb',
    storageBucket: 'chatapp-b5aeb.appspot.com',
    iosClientId: '994080503904-fkctl5t01f56hl91cujq3v4htob9532q.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnt0PiOAWnVqIJg8prDjgS-bAaGbet6BY',
    appId: '1:994080503904:ios:de472e0f2294b36eed6b05',
    messagingSenderId: '994080503904',
    projectId: 'chatapp-b5aeb',
    storageBucket: 'chatapp-b5aeb.appspot.com',
    iosClientId: '994080503904-fkctl5t01f56hl91cujq3v4htob9532q.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
